name: deploy CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
    - name: run deploy.sh
      run: |
        sh deploy.sh
    - name: deploy
      run: git push -f https://@github.com/$PAGE_REPO master:$PAGE_BRAN
      with:
        Username: ${{ 'h69251068k@163.com' }}
        Password: ${{ 'GITHUB_TOKEN' }}
      env: 
        PAGE_REPO: ${{github.repository}}
        PAGE_BRAN: ${{ 'gh-pages' }}
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      
