name: vuepress Document Deploy CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: run deploy.sh
      run: |
        sh /deploy.sh
      env: 
        PAGE_REPO: ${{github.repository}}
        PAGE_BRAN: ${{ 'gh-pages' }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        C_NAME: ${{ 'vuepress-demo.kromalee.xyz' }}
        USER_NAME: ${{'github-actions-ci'}}
        USER_MAIL: ${{'h694251068k@163.com'}}
