name:document deploy CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: check out!
      uses: actions/checkout@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
    - name: run deploy.sh
      run: |
        sh deploy.sh
      env: 
        PAGE_REPO: ${{github.repository}}$ 
        PAGE_BRAN: ${{ 'gh-pages' }}

      
